### PR TITLE
Initialization of repository

### PR DESCRIPTION
**Pull request by castastrophe**
Setting up a rough architecture for an 11ty-based documentation site.

- _site: directory where assets are compiled/published
- docs: directory containing templates and markdown files
  - _includes
  - _layouts
  - articles
  - guides

I also included the licensing, code of conduct, and contribution guides based on what I saw in other WG repos.

### CODE REVIEW

**Comment by castastrophe** [comment]
@Westbrook @bennypowers I was debating integrating rocket into this during the first pass but now I'm thinking maybe we can just move forward with this and add the design tweaks in the next PR?

**Comment by bennypowers** [comment]
The chief benefit to Rocket in our instance is removing doubts. Styles? done. Navigation? finished.

If you have a plan for those and are committed to implementing it, then we're good.

**Comment by castastrophe** [comment]
@bennypowers Oh I definitely want to use a component library like rocket for rendering - I was just debating if it was a good enough first pass without that or if I should hold the PR from review until I get more of the design done.

**Comment by bennypowers** [comment]
Rocket isn't a component library, it's a metaframework and cli over 11ty, web dev server, and rollup. 

I think @dakmor could explain more

**Comment by daKmoR** [comment]
the main benefit would be that we could offload the "theme" e.g. just use what its there and do small adjustments.... and if it improves we can "just" updated.

otherwise, we need to take care of responsive, social media tags/images, production optimizations, ...

I still have this on my todo list 😅  can prioritize it for next week if we want that sooner then later 🤗

**Comment by castastrophe** [comment]
Closing this in favor of @daKmoR's PR.  I opened a fork to bring in the docs and licensing from this though into his set-up.

**Pull request closed without merging**
