### PR TITLE
Using Web Components - Styling article

### LINKED ISSUE #19: [topic] Using web components - styling
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of request

I want to try writing the styling subsection for the "using web components" section of the outline.

I'm thinking of doing an example heavy piece (somewhat similar to [this article I previously wrote](https://dev.to/alangdm/the-quirks-of-shadow-dom-and-how-to-take-advantage-of-them-4cd1) but with a different format.)

Note: I was thinking of writing the Shadow DOM side, but having one for styling non-shadow DOM custom elements would be good too

### Related link(s)

_No response_

### Are you interested in authoring this content?

- [X] Yes

### PR DESCRIPTION
**Pull request by alangdm**
closes #19 

## Description

The article for the using web components styling section of the outline.
Any feedback on the content/examples would be appreciated.

## TBD

- [x] Files: I don't think we had a naming convention for files/folders. I tried to make an educated guess judging from the current content + the outline. Does it look ok?
- [x] Demos: I think we mentioned on the meeting that we should discuss this after a few articles are actually done, but I was thinking of adding mine either through Lit Playground elements or WebComponents.dev. Is there any preference about which to use or how to use it? (i.e. use playground elements through the rocket plugin or having an organization/collection in webcomponents.dev)

### CODE REVIEW

**Comment by Westbrook** [comment]
Looks like you made a good decision on the directory structure: https://deploy-preview-22--web-components-cg.netlify.app/articles/using/styling-shadow/. Do you want to get those "to dos" into this PR, or would it be better to take any high level notes on the content here, merge it in and then follow up on images/demos later?

I like the use of the webcomponents.dev demo, they do some embeds natively, right? Or I think @bennypowers did some MD plugins for similar. If that didn't work, we _might_ look at leveraging features of the SSG we are using, e.g. https://rocket.modern-web.dev/docs/markdown-javascript/preview/, if for nothing else to colocate the demo to the documentation...

**Review by thescientist13 — COMMENTED** [review]
Thoughts from the meeting
1. We can remove the TODOs for now
1. We should add `loading="lazy"` to the `<iframe>`
1. I notice the code sandbox automatically scrolls into the viewport on load by scrolling the page down.  (not sure if this happens for anyone else?). I saw this happen with [Stackblitz too](https://github.com/stackblitz/core/issues/1653), so maybe webcomponents.dev can do the same?

cc: @Westbrook (in case I missed anything)

**Comment by alangdm** [comment]
I've updated the PR with the changes requested 👍

**Review by thescientist13 — APPROVED** [review]
💥 🙏

**Pull request merged**
